# Generated by Django 5.2.9 on 2025-12-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeGap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owasp_category", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("severity", models.CharField(default="moderate", max_length=20)),
                ("recommended_lessons", models.JSONField(default=list)),
                ("practice_questions_needed", models.IntegerField(default=3)),
                ("identified_at", models.DateTimeField(auto_now_add=True)),
                ("addressed", models.BooleanField(default=False)),
                ("addressed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "knowledge_gaps",
                "ordering": ["-identified_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("scenario", "Scenario Based"),
                            ("fill_blank", "Fill in the Blank"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question_text", models.TextField()),
                ("owasp_category", models.CharField(blank=True, max_length=50)),
                ("options", models.JSONField(default=list)),
                ("correct_answer", models.CharField(max_length=500)),
                ("explanation", models.TextField()),
                ("wrong_answer_explanations", models.JSONField(default=dict)),
                ("points", models.IntegerField(default=10)),
                ("time_limit_seconds", models.IntegerField(default=60)),
                ("hint", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_answer", models.CharField(blank=True, max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                ("points_earned", models.IntegerField(default=0)),
                ("time_spent_seconds", models.IntegerField(default=0)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "question_answers",
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("owasp_categories", models.JSONField(default=list)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("time_limit_minutes", models.IntegerField(default=15)),
                ("passing_percentage", models.IntegerField(default=70)),
                ("shuffle_questions", models.BooleanField(default=True)),
                ("show_answers_after", models.BooleanField(default=True)),
                ("is_ai_generated", models.BooleanField(default=True)),
                ("generation_prompt", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Quizzes",
                "db_table": "quizzes",
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("timed_out", "Timed Out"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("max_score", models.IntegerField(default=0)),
                ("percentage", models.FloatField(default=0.0)),
                ("passed", models.BooleanField(default=False)),
                ("correct_count", models.IntegerField(default=0)),
                ("wrong_count", models.IntegerField(default=0)),
                ("skipped_count", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("time_taken_seconds", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "quiz_attempts",
                "ordering": ["-started_at"],
            },
        ),
    ]
