# Generated by Django 5.2.9 on 2025-12-30 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField(unique=True)),
                ("original_title", models.CharField(max_length=500)),
                ("original_content", models.TextField()),
                ("title", models.CharField(max_length=300)),
                ("summary", models.TextField()),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("owasp_categories", models.JSONField(default=list)),
                ("affected_industries", models.JSONField(default=list)),
                ("tags", models.JSONField(default=list)),
                ("action_required", models.BooleanField(default=False)),
                ("action_items", models.JSONField(default=list)),
                ("published_at", models.DateTimeField()),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_breaking", models.BooleanField(default=False)),
                ("views", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "news_articles",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("feed_type", models.CharField(default="rss", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("last_fetched", models.DateTimeField(blank=True, null=True)),
                ("reliability_score", models.FloatField(default=0.8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "news_sources",
            },
        ),
        migrations.CreateModel(
            name="DailyBriefing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("headline", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("threat_level", models.CharField(default="low", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "breaking_alerts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="breaking_briefings",
                        to="news.newsarticle",
                    ),
                ),
                (
                    "other_news",
                    models.ManyToManyField(
                        blank=True,
                        related_name="other_briefings",
                        to="news.newsarticle",
                    ),
                ),
                (
                    "top_story",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="top_story_briefings",
                        to="news.newsarticle",
                    ),
                ),
            ],
            options={
                "db_table": "daily_briefings",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="news.newssource",
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["-published_at"], name="news_articl_publish_d1e015_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["urgency"], name="news_articl_urgency_f74200_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["is_breaking"], name="news_articl_is_brea_e1bffa_idx"
            ),
        ),
    ]
